fix: skip fw directory used by fwupd
Fixes #153 by avoiding the common (in my case) cause of encountering
this error, and improves the error message from:
```
Error: Os { code: 21, kind: IsADirectory, message: "Is a directory" }
```
to:
```
Error removing file "/boot/EFI/nixos/foo": Is a directory (os error 21)
```